version: '3'

services:
  kibana:
    image: kibana:7.3.1
    environment:
      - "LOGGING_QUIET=true"
    links:
      - elasticsearch
    ports:
      - 5601:5601

  elasticsearch:
    image: apm-java/elasticsearch:1.0.0
    build:
      context: infrastructure/elasticsearch
      dockerfile: Dockerfile
    environment:
      - cluster.name=apm-java
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  apm:
    image: apm-java/apm-server:1.0.0
    build:
      context: infrastructure/apm-server
      dockerfile: Dockerfile
    ports:
      - 8200:8200
    links:
      - elasticsearch
      - kibana

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - server
      - apm

  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - apm
